#!/usr/bin/env bash
# Generates self-hosted secrets in .env. The list of keys to mint and
# their generation method (hex32, base64-32, base64url-32, mirror:OTHER)
# is sourced from scripts/schema-vars.sh — itself generated from
# kodus-ai/.env.schema. Add a `kodus: autogen=...` annotation in the
# schema and the next release sync surfaces it here automatically.

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

ENV_FILE=".env"
SCHEMA_VARS_FILE="$(dirname "$0")/schema-vars.sh"

if [ ! -f "$ENV_FILE" ]; then
    echo -e "${RED}Error: .env file not found${NC}"
    exit 1
fi

if [ ! -f "$SCHEMA_VARS_FILE" ]; then
    echo -e "${RED}Error: scripts/schema-vars.sh not found.${NC}"
    echo -e "${YELLOW}This file is generated by kodus-ai's env-sync workflow. Pull the latest installer.${NC}"
    exit 1
fi

# shellcheck source=schema-vars.sh
. "$SCHEMA_VARS_FILE"

mint() {
    local method=$1
    case "$method" in
        hex32)         openssl rand -hex 32 ;;
        base64-32)     openssl rand -base64 32 ;;
        base64url-32)  openssl rand -base64 32 | tr -d '=' | tr '/+' '_-' ;;
        *)             echo "" ;;
    esac
}

# Read the current value of a var from .env (returns empty if absent or empty).
read_env_var() {
    local key=$1
    grep -E "^${key}=" "$ENV_FILE" | head -n1 | sed -E "s/^${key}=//; s/^\"(.*)\"$/\1/; s/^'(.*)'$/\1/"
}

update_or_add_var() {
    local key=$1
    local value=$2

    if grep -q "^${key}=" "$ENV_FILE"; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
        else
            sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
        fi
        echo -e "${GREEN}✓ Updated ${key}${NC}"
    else
        echo "${key}=${value}" >> "$ENV_FILE"
        echo -e "${GREEN}✓ Added ${key}${NC}"
    fi
}

echo -e "${YELLOW}Generating security keys...${NC}"

# Bash 3.2 (macOS default) lacks associative arrays, so we use indirect
# variable expansion: each minted secret is stored as MINTED_<KEY> and
# read back via ${!var:-}. Two passes — primaries first so mirrors can
# resolve them.

for entry in "${KODUS_AUTOGEN_SECRETS[@]}"; do
    key="${entry%%=*}"
    method="${entry#*=}"
    case "$method" in
        mirror:*) continue ;;
    esac
    value=$(mint "$method")
    if [ -z "$value" ]; then
        echo -e "${RED}Error: unknown autogen method '${method}' for ${key}${NC}"
        exit 1
    fi
    printf -v "MINTED_${key}" '%s' "$value"
done

for entry in "${KODUS_AUTOGEN_SECRETS[@]}"; do
    key="${entry%%=*}"
    method="${entry#*=}"
    case "$method" in
        mirror:*)
            target="${method#mirror:}"
            target_var="MINTED_${target}"
            value="${!target_var:-}"
            if [ -z "$value" ]; then
                value=$(read_env_var "$target")
            fi
            if [ -z "$value" ]; then
                echo -e "${RED}Error: cannot mirror ${key} — ${target} is empty.${NC}"
                exit 1
            fi
            printf -v "MINTED_${key}" '%s' "$value"
            ;;
    esac
done

echo -e "\n${YELLOW}Updating .env file...${NC}"
for entry in "${KODUS_AUTOGEN_SECRETS[@]}"; do
    key="${entry%%=*}"
    var="MINTED_${key}"
    update_or_add_var "$key" "${!var}"
done

echo -e "\n${GREEN}All security keys have been generated and updated in .env file!${NC}"
