---
- name: Load qops nftables ruleset
  ansible.builtin.shell: |
    set -euo pipefail
    nft delete table inet {{ host_firewall_nftables_table_name }} 2>/dev/null || true
    nft -f {{ host_firewall_nftables_config_path }}
  args:
    executable: /bin/bash
  changed_when: false
  listen: Load qops nftables ruleset
